spring:
  profiles:
    include:
      - aws
      - credentials
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL}:${DB_PORT}/${DB_USE}?createDatabaseIfNotExist=true
    username: ${DB_ID}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE


logging:
    level:
        org:
          hibernate: info

instagram-clone:
  version: 1.0.0
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
  storage:
    filesystem: ${STORAGE_FS}
  jwt:
    access-token:
      key: ${ACCESS_TOKEN_KEY}
      valid-time: ${ACCESS_TOKEN_VALID_TIME:86400000} # default: 1 day
    refresh-token:
      key: ${REFRESH_TOKEN_KEY}
      valid-time: ${REFRESH_TOKEN_VALID_TIME:432000000} # default: 5 days
