spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_URL:localhost}:${DB_PORT:3306}/${DB_USE:instagram-clone}?createDatabaseIfNotExist=true
    username: ${DB_ID:root}
    password: ${DB_PASSWORD:mariadb}
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    generate-ddl: true
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}