spring:
  profiles:
    group:
      local: common-import,local-import
      eb: common-import,eb-import

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org:
      hibernate: info

instagram-clone:
  version: 1.0.2
---
spring:
  config:
    activate:
      on-profile: common-import
#   profile global property yaml 추가
    import:
      - application-aws.yaml
      - application-credentials.yaml
      - application-database.yaml
---
spring:
  config:
    activate:
      on-profile: local-import
#    local profile에 쓸 property yaml 추가
#    import:
#      - application-some-property-local.yaml
---
spring:
  config:
    activate:
      on-profile: eb-import
#    prod profile에 쓸 property yaml 추가
#    import:
#      - application-some-property-prod.yaml
server:
  port: 5000 # aws elastic beanstalk
