cloud:
    aws:
      s3:
        bucket: # fill in aws s3 bucket name
      region:
        static: # fill in aws region
      stack:
        auto: false
      credentials:
        instanceProfile: true