cloud:
  aws:
    credentials:
      accessKey: # fill in the aws access key
      secretKey: # fill in the aws secret key

instagram-clone:
  mail:
    activation: ${MAIL_ACTIVATION:false}
    username: ${MAIL_USERNAME:none}
    password: ${MAIL_PASSWORD:none}
  jwt:
    access-token:
      key: access_sign_key # fill in the access token sign key
      valid-time: 86400000 # default: 1 day
    refresh-token:
      key: refresh_sign_key # fill in the refresh token sign key
      valid-time: 432000000 # default: 5 days